# Generated by Django 5.0.3 on 2024-03-29 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrangTua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.IntegerField()),
                ('nama', models.CharField(max_length=255)),
                ('tanggal_lahir', models.DateTimeField()),
                ('jenis_kelamin', models.CharField(max_length=1)),
                ('asal_sekolah', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.IntegerField()),
                ('nama', models.CharField(max_length=255)),
                ('tanggal_lahir', models.DateTimeField()),
                ('jenis_kelamin', models.CharField(max_length=1)),
                ('asal_sekolah', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=255)),
                ('ayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayah', to='register.orangtua')),
                ('ibu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ibu', to='register.orangtua')),
            ],
        ),
    ]
