# Generated by Django 5.0.3 on 2024-03-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_orangtua_pekerjaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orangtua',
            name='tanggal_lahir',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='tanggal_lahir',
            field=models.DateField(),
        ),
    ]
