# Generated by Django 5.0.3 on 2024-03-29 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_orangtua_tanggal_lahir_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orangtua',
            name='jenis_kelamin',
        ),
    ]
