# Generated by Django 5.0.3 on 2024-03-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_remove_orangtua_jenis_kelamin'),
    ]

    operations = [
        migrations.AddField(
            model_name='orangtua',
            name='jenis_kelamin',
            field=models.CharField(default='L', max_length=1),
            preserve_default=False,
        ),
    ]
